# encoding: utf-8

Vagrant.configure("2") do |config|
  config.vm.box = "apollo-fat-box"
  config.vm.box_url = "https://s3.amazonaws.com/korczis-vagrant-boxes/apollo-fat-box-v3.box"
  
  config.vm.hostname = "apollo-fat-box"
  
  # PostgreSQL
  config.vm.network "forwarded_port", guest: 5432, host: 5433
  # PostgreSQL
  config.vm.network "forwarded_port", guest: 5432, host: 5433
  
  # CouchDB
  config.vm.network "forwarded_port", guest: 5984, host: 5985
  
  # Redis
  config.vm.network "forwarded_port", guest: 6379, host: 6380
  
  # Tomcaat
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  
  # ElasticSearch
  config.vm.network "forwarded_port", guest: 9200, host: 9201
  
  # Memcached
  config.vm.network "forwarded_port", guest: 11211, host: 11212
  
  # RabbitMQ
  config.vm.network "forwarded_port", guest: 15672, host: 15673
  
  # MongoDB
  config.vm.network "forwarded_port", guest: 27017, host: 27018
  
  # MongoDB Rest
  config.vm.network "forwarded_port", guest: 28017, host: 28018
  
  config.vm.provision :shell, :path => "bootstrap.sh"
end
