# encoding: utf-8

Vagrant.configure("2") do |config|
  config.vm.box = "apollo-fat-box"
  config.vm.box_url = "https://s3.amazonaws.com/korczis-vagrant-boxes/apollo-fat-box-v3.box"
  
  config.vm.hostname = "apollo-fat-box"
  
  config.vm.network "forwarded_port", guest: 5984, host: 5985
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  config.vm.network "forwarded_port", guest: 9200, host: 9201
  config.vm.network "forwarded_port", guest: 15672, host: 15673
  config.vm.network "forwarded_port", guest: 27017, host: 27018
  config.vm.network "forwarded_port", guest: 28017, host: 28018
  
  config.vm.provision :shell, :path => "bootstrap.sh"
end
